name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test with Neovim ${{ matrix.nvim-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest]
        nvim-version: ['v0.9.5', 'v0.10.0', 'nightly']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}

      - name: Install plenary.nvim
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim

      - name: Check Neovim version
        run: |
          nvim --version
          
      - name: Run tests
        run: |
          make test
          
      - name: Run linting (if luacheck available)
        run: |
          if command -v luacheck >/dev/null 2>&1; then
            make lint
          else
            echo "luacheck not available, skipping lint"
          fi
        continue-on-error: true

  test-luacheck:
    name: Lint with luacheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Lua and luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        run: |
          luacheck lua/ tests/ --globals vim --read-globals vim
